# Generated by cucumber-sinatra. (Sun Dec 18 09:08:35 +0000 2011)

ENV['RACK_ENV'] = 'test'
CREATOR_CONTROL_FILE = File.join(File.dirname(__FILE__), "../../bin/repo_creator_control.rb")

require File.join(File.dirname(__FILE__), '..', '..', 'config/init.rb')
require File.join(File.dirname(__FILE__), '..', '..', 'app/yumtags.rb')


require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Yumtags

class YumtagsWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  YumtagsWorld.new
end